getwd()
#install.packages("RMySQL")
library("RMySQL")
conn_db=dbConnect(MySQL(),dbname="tiu",user="root",password="03482",host="localhost",port=3306) 
dbListTables(conn_db)
dbListFields(conn_db,'student')
result_set=dbSendQuery(conn_db,"select * from student")
student_data=fetch(result_set,n=2)
print(student_data)
student_data1=fetch(result_set,n=-1)
print(student_data1)