install.packages("RJDBC")
library(RJDBC)
driver_oracle = JDBC("oracle.jdbc.driver.OracleDriver","C:\\oraclexe\\app\\oracle\\product\\10.2.0\\server\\jdbc\\lib\\ojdbc14.jar")
conn_db = dbConnect(driver_oracle,"jdbc:oracle:thin:@127.0.0.1:1521:XE","hr","hr")
employee_data <- dbGetQuery(conn_db,"SELECT * FROM EMPLOYEES")
print(employee_data)
employee_data <- dbGetQuery(conn_db,"SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL FROM EMPLOYEES WHERE EMPLOYEE_ID IN(109,115)")
print(employee_data)
employee_data <- dbGetQuery(conn_db,"SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL FROM EMPLOYEES WHERE EMPLOYEE_ID BETWEEN 109 AND 115")
print(employee_data)
employee_data1 <- dbReadTable(conn_db,"employees")
print(employee_data1)
dbDisconnect(conn_db)